### ISSUE TITLE
:badarg from :erlang.process_info

### ISSUE THREAD

**Issue by fhunleth** [gabiz/tracer#1]
I think that I have something set up incorrectly, but I'm not sure what. I am going through Erlang distribution to a remote node and working through the README.md. Here's what I get:

```
iex(tracer@0.0.0.0)11> run CallSeq, show_args: true, show_return: true, start_match: &Map.drop/2, node: :"test@nerves.local", max_message_count: 10000, max_queue_size: 10000
** (FunctionClauseError) no function clause matching in Keyword.get/3    
    
    The following arguments were given to Keyword.get/3:
    
        # 1
        {:badrpc,
     {:EXIT,
      {:badarg,
       [{:erlang, :process_info, [#PID<0.160.0>], []},
        {Process, :info, 1, [file: 'lib/process.ex', line: 619]},
        {:rpc, :"-handle_call_call/6-fun-0-", 5, [file: 'rpc.erl', line: 197]}]}}}
    
        # 2
        :dictionary
    
        # 3
        nil
    
    (elixir) lib/keyword.ex:178: Keyword.get/3
    (tracer) lib/process_helper.ex:67: Tracer.ProcessHelper.type/2
    (tracer) lib/process_helper.ex:148: Tracer.ProcessHelper.find_all_children/2
    (tracer) lib/tracer/tools/tool_call_seq.ex:62: Tracer.Tool.CallSeq.init/1
    (tracer) lib/tracer.ex:109: Tracer.run/2
```
I have no problems running `:observer` or anything else on the remote node. The error above looks legit since `#PID<0.160.0>` is my current IEx session on `tracer@0.0.0.0`. I assume that a remote pid should have been passed above so I'm thinking that I skipped over something important. Do you have any clues?

**Comment by gabiz** [comment]
When the `process:` option is missing then the `self()` process is assumed, however self is in the local node and tracer is trying to locate it in the remote node so is failing.
You need to specify a process id to trace in the remote node by passing an option like `process: pid(165, 151, 0)`.
You can provide instead a registered name to trace on the remote node.

**Comment by fhunleth** [comment]
Thanks - I'm not sure how I missed the `process:` option, but that makes total sense. I'll retry.

**Comment by pmargreff** [comment]
Seems legit, I'm having the same problem. 
node 1: 
```
iex(node1@127.0.0.1)23> self
#PID<0.109.0>
```
node 2: 
```
iex(tracer3@127.0.0.1)32> Node.list()
[:"node1@127.0.0.1"]
iex(tracer3@127.0.0.1)33> run CallSeq, max_message_count: 100_000, max_queue_size: 100_000, node: :"node1@127.0.0.1", process: pid(0, 109, 0)
** (FunctionClauseError) no function clause matching in Keyword.get/3

    The following arguments were given to Keyword.get/3:

        # 1
        {:badrpc,
         {:EXIT,
          {:badarg,
           [
             {:erlang, :process_info, [#PID<0.109.0>], []},
             {Process, :info, 1, [file: 'lib/process.ex', line: 746]},
             {:rpc, :"-handle_call_call/6-fun-0-", 5, [file: 'rpc.erl', line: 197]}
           ]}}}

        # 2
        :dictionary

        # 3
        nil

    Attempted function clauses (showing 1 out of 1):

        def get(keywords, key, default) when is_list(keywords) and is_atom(key)

    (elixir) lib/keyword.ex:195: Keyword.get/3
    (tracer) lib/process_helper.ex:67: Tracer.ProcessHelper.type/2
    (tracer) lib/process_helper.ex:148: Tracer.ProcessHelper.find_all_children/2
    (tracer) lib/tracer/tools/tool_call_seq.ex:62: Tracer.Tool.CallSeq.init/1
    (tracer) lib/tracer.ex:109: Tracer.run/2
```

Any suggestions?
