### ISSUE TITLE
Does this still work? I can't get the examples to work

### ISSUE THREAD

**Issue by dzfranklin** [gabiz/tracer#3]
For example, 
```
Interactive Elixir (1.11.0) - press Ctrl+C to exit (type h() ENTER for help)

iex(1)> use Tracer

iex(2)> run CallSeq, show_args: true, show_return: true, start_match: &Map.new/1,  max_message_count: 10000, max_queue_size: 10000
warning: Supervisor.start_child/2 with a list of args is deprecated, please use DynamicSupervisor instead
  (elixir 1.11.0) lib/supervisor.ex:826: Supervisor.start_child/2
  (tracer 0.1.1) lib/tracer_server.ex:70: Tracer.Server.start_tool/1
  (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
  (elixir 1.11.0) src/elixir.erl:278: :elixir.recur_eval/3
  (elixir 1.11.0) src/elixir.erl:263: :elixir.eval_forms/3
  (iex 1.11.0) lib/iex/evaluator.ex:261: IEx.Evaluator.handle_eval/5
  (iex 1.11.0) lib/iex/evaluator.ex:242: IEx.Evaluator.do_eval/3
  (iex 1.11.0) lib/iex/evaluator.ex:220: IEx.Evaluator.eval/3
  (iex 1.11.0) lib/iex/evaluator.ex:102: IEx.Evaluator.loop/1
  (iex 1.11.0) lib/iex/evaluator.ex:32: IEx.Evaluator.init/4
  (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

started tracing
:ok

iex(3)> Map.new
%{}

iex(4)> done tracing: tracing_timeout 30000
```

**Comment by dzfranklin** [comment]
Nevermind, I made the silly mistake of calling Map.new/0 instead of Map.new/1
